name: GitHub Actions Test
run-name: ${{ github.actor }}
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.24.5'
      - name: go version
        run: go version
