name: Release

on: [push]

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.5'

      - name: Build binary
        env:
          GOOS: linux
          GOARCH: amd64
        run: |
          binary_name="test-go-release"
          output_name="${binary_name}_linux_amd64"
          
          go build -o "${output_name}" main.go
          
          # アーカイブを作成
          tar -czf "${output_name}.tar.gz" "${output_name}"

      - name: Create Release with gh
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release create release-test-v1 \
            --title "Release release-test-v1" \
            --notes "## Changes in release-test-v1

          自動生成されたリリースです。

          ### ダウンロード
          - Linux (amd64): test-go-release_linux_amd64.tar.gz" \
            test-go-release_linux_amd64.tar.gz