name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.5'

      - name: Get version from tag
        id: version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Build binary
        env:
          GOOS: linux
          GOARCH: amd64
        run: |
          binary_name="test-go-release"
          output_name="${binary_name}_linux_amd64"
          
          go build -o "${output_name}" main.go
          
          # アーカイブを作成
          tar -czf "${output_name}.tar.gz" "${output_name}"

      - name: Create Release with gh
        run: |
          gh release create ${{ steps.version.outputs.VERSION }} \
            --title "Release ${{ steps.version.outputs.VERSION }}" \
            --notes "## Changes in ${{ steps.version.outputs.VERSION }}